### ISSUE TITLE
Server incorrectly sends 500 instead of 404 on pages that don't exitst

### ISSUE THREAD

**Issue by 1ctinus** [tycrek/tycrek.com#1]
lets say,
https://tycrek.com/7236598723657862347865783/
obviously doesnt exist, so it should send 404, not 500.

**Comment by tycrek** [comment]
![image](https://user-images.githubusercontent.com/29926144/111055813-da453080-8436-11eb-8766-b38a7377b214.png)

@1ctinus it was trying to render pages that didn't exist (artifact from duplicating my other sites repo) because I took out the stuff it didn't need, since this is a single-page site. Also yes, there are much easier ways to host a single page but I wanted to over-complicate it lol

Long story short, force it to render `index` no matter the route (css is still passed properly)
